### ISSUE TITLE
Can't parse JSON Stack Begin

### ISSUE THREAD

**Issue by zxcobakeis** [BillsTheGod/V3RMILLION_PROJECTS#7]
Hi, I found your script on rbxscript, but it seems outdated and is giving errors:

"Can't parse JSON
Stack Begin
Script 'CorePackages.JestGlobals', Line 892
Script [string 'OvvlPWM'], Line 11 - function getChat
Script [string 'OvvlPWM'], Line 18
Script 'CorePackages.JestGlobals', Line 605
Stack End"

Could you update the script with a fix for this problem or at least point out the cause of the error?

**Comment by BillsTheGod** [comment]
I am no longer actively working on this. It's been quite some time since I last updated or maintained it, and unfortunately, I won't be able to provide any further support or fixes.
